# Generated by Django 4.1.7 on 2023-02-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.SmallIntegerField(choices=[(1, 'Heigh'), (2, 'Medium'), (3, 'Low')], default=3)),
                ('status', models.CharField(choices=[('c', 'Completed'), ('w', 'Waiting'), ('p', 'On Progress')], default='w', max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
